// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG63m59sPFezz2GHDIvSuY1guueSD--XY',
    appId: '1:443802490180:web:6f891ebdcdeac2ae927311',
    messagingSenderId: '443802490180',
    projectId: 'firebasicsproject',
    authDomain: 'firebasicsproject.firebaseapp.com',
    storageBucket: 'firebasicsproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4y8gX6_sTjaSmVcuHFuKFAKmPR-vJpyg',
    appId: '1:443802490180:android:21abde55a0083469927311',
    messagingSenderId: '443802490180',
    projectId: 'firebasicsproject',
    storageBucket: 'firebasicsproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2mML9mjkXg2yhVljdJK0Nkbf29EJQIkI',
    appId: '1:443802490180:ios:5d15d4b057337a0d927311',
    messagingSenderId: '443802490180',
    projectId: 'firebasicsproject',
    storageBucket: 'firebasicsproject.appspot.com',
    iosBundleId: 'com.example.firebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2mML9mjkXg2yhVljdJK0Nkbf29EJQIkI',
    appId: '1:443802490180:ios:d11a8cf7e5551cb7927311',
    messagingSenderId: '443802490180',
    projectId: 'firebasicsproject',
    storageBucket: 'firebasicsproject.appspot.com',
    iosBundleId: 'com.example.firebaseBasics.RunnerTests',
  );
}
